<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My New Test Plugin Plugin</title>
</head>
<body>
    <h1>Welcome to My New Test Plugin Plugin!</h1>
    <p>This is a default view generated by the CLI.</p>
</body>
</html>