<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Plugin</title>
</head>
<body>
    <h1>Welcome to Home Plugin!</h1>
    <p>This is a default view generated by the CLI.</p>

    <?php
        $actionFilterHelper->doAction('top_page_slider');
    ?>

</body>
</html>